Dynamic test suite creation using option --create-suite
lop-devops/tests pull request #317
Opened 2024-03-07 17:38 UTC by spoorthys1303

User can run dynamic test suite created by test cases list provided to --create-suite option This option works for host tests.
Input testcases should have full path of avocado misc tests seprated by comma If --run-suite option is provided, it will run the existing test suite provided by user

2024-03-07 17:39 UTC, spoorthys1303 commented
Test results :
**only --create-suite**
`# python avocado-setup.py --create-suite avocado-misc-tests/perf/perf_pmu.py,avocado-misc-tests/perf/perf_hv_gpci.py 
22:55:32 INFO    : Check for environment
22:55:32 INFO    : Creating temporary mux dir
22:55:33 INFO    : 
22:55:33 INFO    : Running Host Tests Suite dynamic_test_suite_perf_pmu
22:55:33 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py --force-job-id 7698c84e4d18e11f8add181ff88635ac21a491cb  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 7698c84e4d18e11f8add181ff88635ac21a491cb
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-03-07T22.55-7698c84/job.log
 (1/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_config_PMU_sysfs: STARTED
 (1/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_config_PMU_sysfs: CANCEL: CONFIG_PMU_SYSFS not set. (0.05 s)
 (2/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_config_PPC_RTAS: STARTED
 (2/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_config_PPC_RTAS: PASS (0.66 s)
 (3/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_cpu_event_count: STARTED
 (3/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_cpu_event_count: PASS (0.05 s)
 (4/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_hv_24x7_event_count: STARTED
 (4/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_hv_24x7_event_count: PASS (0.05 s)
 (5/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_imc_event_count: STARTED
 (5/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_imc_event_count: SKIP: This test is for PowerNV
 (6/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_thread_event_count: STARTED
 (6/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_thread_event_count: SKIP: This test is for PowerNV
 (7/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_nest_cpumask: STARTED
 (7/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_nest_cpumask: SKIP: This test is for PowerNV
 (8/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_core_cpumask: STARTED
 (8/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_core_cpumask: SKIP: This test is for PowerNV
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 4 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-03-07T22.55-7698c84/results.html
JOB TIME   : 44.08 s
22:56:19 INFO    : 
22:56:19 INFO    : 
22:56:19 INFO    : Running Host Tests Suite dynamic_test_suite_perf_hv_gpci
22:56:19 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_hv_gpci.py --force-job-id 0accc6cbb0bdc005945f482cbb5a63e3fc8032c4  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 0accc6cbb0bdc005945f482cbb5a63e3fc8032c4
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-03-07T22.56-0accc6c/job.log
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_hv_gpci.py:perf_hv_gpci.test_gpci_events: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_hv_gpci.py:perf_hv_gpci.test_gpci_events: FAIL: perf hv_gpci: some of the events failed,refer to log (3.13 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-03-07T22.56-0accc6c/results.html
JOB TIME   : 54.10 s

Test summary:
1-/root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_hv_gpci.py:perf_hv_gpci.test_gpci_events: FAIL
22:57:16 INFO    : 
22:57:16 INFO    : Summary of test results can be found below:
TestSuite                                                                                TestRun    Summary
 
host_dynamic_test_suite_perf_pmu                                                         Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2024-03-07T22.55-7698c84/job.log
| PASS 3 || CANCEL 1 || ERRORS 0 || FAILURES 0 || SKIP 4 || WARN 0 || INTERRUPT 0 |
 
host_dynamic_test_suite_perf_hv_gpci                                                     Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2024-03-07T22.56-0accc6c/job.log
| PASS 0 || CANCEL 0 || ERRORS 0 || FAILURES 1 || SKIP 0 || WARN 0 || INTERRUPT 0 |
22:57:16 INFO    : Removing temporary mux dir`

2024-03-07 17:40 UTC, spoorthys1303 commented
**with --create-suite and --run-suite** 

`# python avocado-setup.py --create-suite avocado-misc-tests/perf/perf_basic.py,avocado-misc-tests/perf/perf_pmu.py,avocado-misc-tests/perf/perf_hv_gpci.py   --run-suite host_em_sanity
22:57:25 INFO    : Check for environment
22:57:25 INFO    : Creating temporary mux dir
22:57:26 INFO    : 
22:57:26 INFO    : Running Host Tests Suite em_sanity_em_cpupower
22:57:26 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/em_cpupower.py --force-job-id 8202ba4d57ee89da1b2c8b6243e6492bb0601907  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 8202ba4d57ee89da1b2c8b6243e6492bb0601907
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-03-07T22.57-8202ba4/job.log
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/em_cpupower.py:cpupower.test: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/em_cpupower.py:cpupower.test: SKIP: This test is not supported on PowerVM platform
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 1 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-03-07T22.57-8202ba4/results.html
JOB TIME   : 17.91 s
22:57:46 INFO    : 
22:57:46 INFO    : 
22:57:46 INFO    : Running Host Tests Suite dynamic_test_suite_perf_basic
22:57:46 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py --force-job-id 8d82e160975bece6dc02e20981105bdbd4fa3e53  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : 8d82e160975bece6dc02e20981105bdbd4fa3e53
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-03-07T22.57-8d82e16/job.log
 (01/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_help: STARTED
 (01/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_help: PASS (0.38 s)
 (02/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_version: STARTED
 (02/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_version: PASS (0.38 s)
 (03/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_version_test: STARTED
 (03/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_version_test: PASS (0.38 s)
 (04/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_list: STARTED
 (04/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_list: PASS (0.67 s)
 (05/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_record: STARTED
 (05/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_record: PASS (6.67 s)
 (06/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_cmd_kallsyms: STARTED
 (06/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_cmd_kallsyms: PASS (0.54 s)
 (07/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_cmd_annotate: STARTED
 (07/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_cmd_annotate: PASS (132.45 s)
 (08/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_cmd_evlist: STARTED
 (08/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_cmd_evlist: PASS (2.46 s)
 (09/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_cmd_script: STARTED
 (09/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_cmd_script: PASS (2.59 s)
 (10/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_stat: STARTED
 (10/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_stat: PASS (5.39 s)
 (11/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_bench: STARTED
 (11/11) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_basic.py:PerfBasic.test_perf_bench: PASS (6.16 s)
RESULTS    : PASS 11 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-03-07T22.57-8d82e16/results.html
JOB TIME   : 235.47 s
23:01:44 INFO    : 
23:01:44 INFO    : 
23:01:44 INFO    : Running Host Tests Suite dynamic_test_suite_perf_pmu
23:01:44 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py --force-job-id f1dc27bb39770f1ce8a763444da0240367fe2c3d  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : f1dc27bb39770f1ce8a763444da0240367fe2c3d
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-03-07T23.01-f1dc27b/job.log
 (1/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_config_PMU_sysfs: STARTED
 (1/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_config_PMU_sysfs: CANCEL: CONFIG_PMU_SYSFS not set. (0.05 s)
 (2/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_config_PPC_RTAS: STARTED
 (2/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_config_PPC_RTAS: PASS (0.71 s)
 (3/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_cpu_event_count: STARTED
 (3/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_cpu_event_count: PASS (0.05 s)
 (4/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_hv_24x7_event_count: STARTED
 (4/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_hv_24x7_event_count: PASS (0.05 s)
 (5/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_imc_event_count: STARTED
 (5/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_imc_event_count: SKIP: This test is for PowerNV
 (6/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_thread_event_count: STARTED
 (6/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_thread_event_count: SKIP: This test is for PowerNV
 (7/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_nest_cpumask: STARTED
 (7/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_nest_cpumask: SKIP: This test is for PowerNV
 (8/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_core_cpumask: STARTED
 (8/8) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_pmu.py:PerfBasic.test_core_cpumask: SKIP: This test is for PowerNV
RESULTS    : PASS 3 | ERROR 0 | FAIL 0 | SKIP 4 | WARN 0 | INTERRUPT 0 | CANCEL 1
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-03-07T23.01-f1dc27b/results.html
JOB TIME   : 44.39 s
23:02:31 INFO    : 
23:02:31 INFO    : 
23:02:31 INFO    : Running Host Tests Suite dynamic_test_suite_perf_hv_gpci
23:02:31 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_hv_gpci.py --force-job-id f6142b53649334b1aed683738c86013039cfb8a4  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : f6142b53649334b1aed683738c86013039cfb8a4
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-03-07T23.02-f6142b5/job.log
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_hv_gpci.py:perf_hv_gpci.test_gpci_events: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/perf/perf_hv_gpci.py:perf_hv_gpci.test_gpci_events:  [...]

2024-03-07 17:41 UTC, spoorthys1303 commented
**only --run-suite**

# python avocado-setup.py --run-suite host_em_sanity
23:04:31 INFO    : Check for environment
23:04:31 INFO    : Creating temporary mux dir
23:04:32 INFO    : 
23:04:32 INFO    : Running Host Tests Suite em_sanity_em_cpupower
23:04:32 INFO    : Running: /usr/local/bin/avocado run --max-parallel-tasks=1 /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/em_cpupower.py --force-job-id a7d7cde8cb23801761edbf2f5651f3cdc24aa871  --job-results-dir /root/avocado-fvt-wrapper/results
JOB ID     : a7d7cde8cb23801761edbf2f5651f3cdc24aa871
JOB LOG    : /root/avocado-fvt-wrapper/results/job-2024-03-07T23.04-a7d7cde/job.log
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/em_cpupower.py:cpupower.test: STARTED
 (1/1) /root/avocado-fvt-wrapper/tests/avocado-misc-tests/cpu/em_cpupower.py:cpupower.test: SKIP: This test is not supported on PowerVM platform
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 1 | WARN 0 | INTERRUPT 0 | CANCEL 0
JOB HTML   : /root/avocado-fvt-wrapper/results/job-2024-03-07T23.04-a7d7cde/results.html
JOB TIME   : 18.06 s
23:04:52 INFO    : 
23:04:52 INFO    : Summary of test results can be found below:
TestSuite                                                                                TestRun    Summary
 
host_em_sanity_em_cpupower                                                               Run        Successfully executed
/root/avocado-fvt-wrapper/results/job-2024-03-07T23.04-a7d7cde/job.log
| PASS 0 || CANCEL 0 || ERRORS 0 || FAILURES 0 || SKIP 1 || WARN 0 || INTERRUPT 0 |
23:04:52 INFO    : Removing temporary mux dir

2024-03-13 10:06 UTC, abdhaleegit requested changes
So the name of the new suite will be decided by script or user given.  

I mean --create-suite <cfgname.cfg> is the rite way 

also  just --create-suite should create the file and not run the test (as per logs)

--create-suite with --run-suite should both create and run the test

also please paste here the final cfg file here

2024-03-13 10:30 UTC, spoorthys1303 commented
@abdhaleegit Name of the suite will be decided by the script as user will pass the test cases as arguments for --create-suite 
hence I have coded such that , when user pass this option it will create the test suite and run the suite . 

meanwhile creating suite can be achieved manually for given list of test by the user instead of using the option --create-suite

2024-03-13 11:21 UTC, spoorthys1303 commented
```
python avocado-setup.py --create-run-suite avocado-misc-tests/perf/perf_pmu.py,avocado-misc-tests/perf/perf_hv_gpci.py,avocado-misc-tests/perf/perf_basic.py

# cat config/tests/host/dynamic_test_suite.cfg 
avocado-misc-tests/perf/perf_pmu.py
avocado-misc-tests/perf/perf_hv_gpci.py
avocado-misc-tests/perf/perf_basic.py
```

2024-03-13 11:26 UTC, spoorthys1303 commented
https://github.com/lop-devops/tests/issues/320

2024-03-18 06:18 UTC, sacsant commented
As mentioned by Abdul, --create-suite or --create-run-suite is misleading. 
We should keep the logic clean as follows
--create-suite -> should only create a cfg file
--run-suite -> execute only
--create-suite & --run-suite should create and then run the tests

2024-03-18 07:26 UTC, spoorthys1303 commented
@sacsant In this case, should we expect user to provide the suite name?

2024-03-18 08:30 UTC, sacsant commented
> @sacsant In this case, should we expect user to provide the suite name?

Depends on how generic we want this option to be. If this option should only be used in a DevOps environment, the cfg name can be dynamically generated.

If we want end user to also use it then the user should provide it. In this case we should add  code to validate the user specified config name to ensure it does not clash with any existing cfgs

2024-03-18 09:58 UTC, spoorthys1303 commented
@sacsant @abdhaleegit The intention of this feature is to run different combination of host tests on SUT provided by user/devops in the CLI.
Hence creating a temporary test suite will be a internal mechanism to facilitate the test run. 
Thus, changing the option name to --run-tests will suffice ?

2024-03-19 05:56 UTC, spoorthys1303 commented
option name is now --run-tests

2024-03-19 07:51 UTC, PraveenPenguin approved these changes

2024-03-26 06:19 UTC, merged