Dynamic input file generation for nvme and nvmf devices v2
lop-devops/tests pull request #318
Opened 2024-03-08 16:33 UTC by manvanthar

Code changes include
1. review comments from PR303
2. changes to differentiate FC and nvmf devices.
3. new logic to identify nvmf config and devices
4. logic to differentiate b/w nvmf RHEL8 and other Distros
5. correction of pci_devices values

2024-03-08 16:34 UTC, manvanthar commented
#python3 ./pci_info.py --show-info
[{'adapter_description': 'Emulex Corporation LPe31000/LPe32000 Series '
                         '16Gb/32Gb Fibre Channel Adapter',
  'adapter_id': '10df:e300:1014:0615',
  'adapter_type': 'nvmf',
  'class': 'scsi_host',
  'disks': ['/dev/mapper/eui.a8000000000000e900507608108001b3',
            '/dev/mapper/eui.a8000000000000ea00507608108001b3',
            '/dev/mapper/eui.a8000000000000eb00507608108001b3',
            '/dev/mapper/eui.a8000000000000ec00507608108001b3',
            '/dev/mapper/eui.a8000000000000ed00507608108001b3'],
  'driver': ['nvme_fc', 'nvme_fabrics', 'nvme_core'],
  'firmware': '14.0.574.7',
  'functions': ['0014:70:00.0', '0014:70:00.1'],
  'infiniband_interfaces': [],
  'interfaces': ['host1', 'host2'],
  'is_root_disk': False,
  'mpath_disks': ['/dev/mapper/eui.a8000000000000e900507608108001b3',
                  '/dev/mapper/eui.a8000000000000ea00507608108001b3',
                  '/dev/mapper/eui.a8000000000000eb00507608108001b3',
                  '/dev/mapper/eui.a8000000000000ec00507608108001b3',
                  '/dev/mapper/eui.a8000000000000ed00507608108001b3'],
  'mpath_wwids': ['eui.a8000000000000e900507608108001b3',
                  'eui.a8000000000000ea00507608108001b3',
                  'eui.a8000000000000eb00507608108001b3',
                  'eui.a8000000000000ec00507608108001b3',
                  'eui.a8000000000000ed00507608108001b3'],
  'pci_root': '0014:70:00',
  'slot': 'U78D3.001.WZS067A-P1-C12'}]

#python3 ./pci_info.py --create-config
10:16:58 INFO    : python avocado-setup.py --run-suite host_io_nvmf_rhel8_0014_70_00_fvt --input-file io_input.txt
# cat io_input.txt 
[io_nvmf_rhel8_0014_70_00_fvt]
disk = "/dev/mapper/eui.a8000000000000e900507608108001b3"
lv_disks = "/dev/mapper/eui.a8000000000000ea00507608108001b3"
htx_disks = "/dev/mapper/eui.a8000000000000eb00507608108001b3"
disks = "/dev/mapper/eui.a8000000000000ec00507608108001b3 /dev/mapper/eui.a8000000000000ed00507608108001b3"
wwids = "eui.a8000000000000e900507608108001b3 eui.a8000000000000ea00507608108001b3 eui.a8000000000000eb00507608108001b3 eui.a8000000000000ec00507608108001b3 eui.a8000000000000ed00507608108001b3"
pci_device = "0014:70:00.0"
pci_devices = "0014:70:00.0 0014:70:00.1"
module = "nvme_fc nvme_fabrics nvme_core"
dir = "/mnt"
lv_size = "10G"
count = 30
fsstress_loop = 3
num_of_dlpar = 30
num_of_hotplug = 20
iteration = 30
run_type = "rpm"
manageSystem = ""
userid = ""
password = ""
hmc_username = ""
hmc_pwd = ""
htx_rpm_link = ""
switch_name = ""

2024-03-13 09:49 UTC, abdhaleegit requested changes
rhel8x  has  /dev/mapper/mpathx has nvmf device format
rhel9x and sles15x  has /dev/nvme0n1 as nvmf device format

hope this is taken care for all above, currently we have io_nvmf_rhel8x.cfg and io_nvmf.cfg  --> for all os other than 8x

2024-03-13 09:49 UTC, abdhaleegit commented on lib/pci.py
> +                if root_disk in disk:
any need to change it back ?

2024-03-13 09:49 UTC, abdhaleegit commented on lib/pci.py
> +                                                       interface))]
any reason to revert back to old code ?

2024-03-14 04:46 UTC, abdhaleegit commented
@manvanthar remove the revert commit and rebase your branch to master

2024-03-14 08:14 UTC, PraveenPenguin commented on lib/pci.py
> +    wwid_pattern = r"eui\.[a-fA-F\d]+"
is `eui` always be wildcard?

2024-03-25 07:32 UTC, abdhaleegit approved these changes
LGTM,  we can merge after praveens changes are pushed

2024-03-25 07:32 UTC, abdhaleegit commented on lib/helper.py
> +        return False
I think we are good here, as the python platform module is actully reading /etc/os-release  and these values will not change with custom kernel

2024-03-25 12:09 UTC, manvanthar commented on lib/pci.py
> +    pci_domain_path = os.path.join(sys_devices_path, 'pci' + pci_domain)
Done

2024-03-26 05:18 UTC, PraveenPenguin approved these changes

2024-03-26 05:19 UTC, merged