Dynamic input and cfg file creation for vNIC interface.
lop-devops/tests pull request #332
Opened 2024-06-20 01:03 UTC by FarooqAbdulla02

This code supports to dynamically create "configuration file" and
"input file" for virtual interface with few required parameters.

2024-06-20 01:04 UTC, FarooqAbdulla02 commented
A. show info for virtual interface :
# ./pci_info.py --vnic env3 --show-info
[{'adapter_type': 'vnic',
'driver': 'ibmvnic',
'interfaces': ['env3', 'env4', 'env5'],
'mac_id': '02af7e50c203',
'macaddress': '02:af:7e:50:c2:03',
'public_interface_ip': '9.40.192.184'}]

B. create config without additional params:
# ./pci_info.py --vnic env3 --create-config
19:39:41 INFO : python avocado-setup.py --run-suite host_io_env3_vnic_dymamic_fvt --input-file io_input.txt
# cat io_input.txt
[io_env3_vnic_dymamic_fvt]
host_interfaces = "env3 env4"
bond_interfaces = "env3 env4"
htx_host_interfaces = "env3 env4"
host_public_ip = "9.40.192.184"
interface = "env3"
module = "ibmvnic"
macaddress = "02:af:7e:50:c2:03"
mac_id = "02af7e50c203"

C. create config with additional params
#./pci_info.py --vnic env3 --additional-params device_ip=192.168.100.184,peer_ip=192.168.100.104,netmask=255.255.255.0,
host_ip=192.168.100.184,netmasks=255.255.255.0,peer_ips="192.168.100.104 192.168.110.104",peer_interfaces="env4 env5" --create-config

  19:35:11 INFO    : python avocado-setup.py --run-suite host_io_env3_vnic_dymamic_fvt --input-file io_input.txt
    # cat io_input.txt
    [io_env3_vnic_dymamic_fvt]
    host_interfaces = "env3 env4"
    bond_interfaces = "env3 env4"
    htx_host_interfaces = "env3 env4"
    host_public_ip = "9.40.192.184"
    interface = "env3"
    module = "ibmvnic"
    macaddress = "02:af:7e:50:c2:03"
    mac_id = "02af7e50c203"
    device_ip = 192.168.100.184
    peer_ip = 192.168.100.104
    host_ip = 192.168.100.184
    netmask = 255.255.255.0
    netmasks = 255.255.255.0
    peer_ips = 192.168.100.104 192.168.110.104
    host_ips = "110.10.10.212 111.10.10.212"
    peer_interfaces = env4 env5

2024-06-28 13:17 UTC, abdhaleegit requested changes
does it not affect the old pci network bucket... looks like a little change in the create_config flow

2024-06-28 13:17 UTC, abdhaleegit commented on config/wrapper/pci_input.conf
> +[io_vnic_dynamic_fvt]
just keep this name as io_vnic_fvt

2024-06-28 13:17 UTC, abdhaleegit commented on lib/virtual.py
> +        print(f'Interface not found {e}')
instead print raise the error

2024-06-28 13:17 UTC, abdhaleegit commented on pci_info.py
> +def create_config_inputs(orig_cfg, new_cfg, inputfile, interface, config_type):
you do not need to pass old and and new cfg file name.. instead it should fetch default cfg files in fvt wrapper and append the interface name like io_vnic_env3_fvt.cfg to the file also.. to input file io-input.txt .. not sure why you are passing them as parameter

2024-10-18 06:35 UTC, abdhaleegit commented
@FarooqAbdulla02 

As discussed, couple of suggestions:

1. Include also the constant parameters values into the final input file, also fetch is_mlx_driver, default tx/rx etc and ommit slot/sriovadapter/port params as vnic is already created
2. Add support to create input file with out vnic interface specified i.e just — vnic should collect available vnic interface data into input.. this is must for end to end flow
3. Add a new bucket io_vnic_stress_fvt.cfg containing only runnable tests with dynamic inputfile .. remove dependency of hmc/vios (device add/delete no in scope)
4. Follow the old naming conventions for bucket name I.e [io_vnic_env3_fvt] .. as per your code it follows this [io_env3_vnic_dymamic_fvt]
5. Make sure the it creates input/cfg for mix of vnic and sriov in single lpar
6. finally rebase the code .. it shows merge conflict..  

Note: make sure the API's works for both RHEL and SLES O

2024-11-12 11:01 UTC, abdhaleegit commented
close this one once the new PR is merged

2024-11-15 11:09 UTC, FarooqAbdulla02 commented
same issue has been tracked on https://github.com/lop-devops/tests/pull/341 and closing this as duplicate.

2024-11-15 11:09 UTC, closed without merging